# fly.toml app configuration file generated for backend-development-dry-haze-7874 on 2023-12-17T21:42:09+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "backend-development-dry-haze-7874"
primary_region = "sin"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[http_service.tls_options]
  alpn = ["h2", "http/1.1"]
  versions = ["TLSv1.2", "TLSv1.3"]
  default_self_signed = false

[env]
  MYSQL_ATTR_SSL_CA = "/etc/ssl/certs/ca-certificates.crt"